douyu/jupiter

CONTRIBUTING.md
README.md

- fix a few typos that I saw in this repo
- nope
- ditto
PS: thanks for contributing a great repo to the community ! I am looking forward to learning more from it.

chore(README): fix typos

---

tools/jupiter/new/templates/go.mod.tmpl
tools/jupiter/new/templates/internal/app/engine/engine.go.tmpl

jupiter Scaffold repair
1.Change the directory structure of the engine in the scaffold
2.Optimization go.mod

Scaffold repair

---

README.md

fix indent in doc

---

tools/jupiter/new/templates/Makefile

fix: new project makefile

---

signal_linux.go

clean up: delete useless code

---

go.mod

remove useless package in go.mod 
run: go mod tidy

rm: useless package go.mod

---

pkg/server/xgin/server.go

rm: debug code

---

pkg/server/xecho/server.go
pkg/server/xgin/server.go
pkg/server/xgrpc/server.go

supports dynamic port
Fixed #51 
`
[jupiter.server.http]
port = 0
[jupiter.server.grpc]
port = 0
`

auto server port

---

go.sum
pkg/xlog/api.go
pkg/xlog/buffer_syncer.go
pkg/xlog/buffer_syncer_bench_test.go
pkg/xlog/buffer_syncer_test.go
pkg/xlog/log.go

xlog support buffer write

---

pkg/server/xgin/config.go
pkg/server/xgin/server.go

Fix gin mode and change default mode to "release"

fix: move gin.setmode before gin.new

---

pkg/client/redis/redis_cmds.go

fix: issue #67 and add HIncrByWithErr method

---

.github/workflows/go.yml

add test  strategy to  actions workflows, and  push coverage.txt to codecov
github actions faster than travisCI
note: do not forget adding CODECOV_TOKEN  to secrets on github settings.

Feat GitHub action

---

.github/ISSUE_TEMPLATE/bug_report.md

add: ISSUE_TEMPLATE go env tips

---

Makefile

fix git rev-parse

---

README.md

patch update qr size

---

pkg/util/xgo/parallel.go

optimize RestrictParallelWithErrorChan method
The original method will create redundant goroutine (n= len(tasks)),
the new method will only create the specified number of goroutine (n = param.concurrency)
when  concurrency< len(tasks), will create goroutine unnecessary.
go test jupiter/pkg/util/xgo/parallel_test.go

pref: optimize RestrictParallelWithErrorChan method

---

pkg/client/redis/cluster_cmds.go
pkg/client/redis/redis_cmds.go
pkg/conf/conf.go
pkg/util/xcast/interface.go
pkg/util/xgo/parallel.go
pkg/util/xmap/map.go
pkg/util/xstring/string.go
pkg/xlog/rotate/lumberjack_darwin.go

style(*): fix some lint error

---

pkg/client/redis/config.go
pkg/client/redis/redis.go
pkg/client/redis/redis_cmds.go

optimize code

---

pkg/client/grpc/balancer/p2c/least_loaded.go
pkg/client/grpc/balancer/p2c/least_loaded_test.go
pkg/util/xp2c/leastloaded/least_loaded.go
pkg/util/xp2c/leastloaded/least_loaded_test.go
pkg/util/xp2c/p2c.go

Grpc load balance support `p2c with least loaded` algorithm.
```bash
ok  	github.com/douyu/jupiter/pkg/client/grpc/balancer/p2c	2.356s	coverage: 92.9% of statements
```

[feat] support p2c with least loaded algorithm.

---

example/all/cmd/demo/main.go
example/grpc/etcd/etcd-server/main.go
jupiter.go
pkg/constant/service.go
pkg/defers/defer.go
pkg/defers/defer_test.go
pkg/govern/http.go
pkg/registry/etcdv3/registry.go
pkg/server/server.go
pkg/server/xecho/server.go
pkg/server/xgin/server.go
pkg/server/xgrpc/server.go
pkg/util/xdefer/stack.go

Impove governor, supports:
- customize governor port from configuration
- random governor port when no configuration provide
- register governor service

impove governor

---

jupiter.go
pkg/util/xcycle/lifecycle.go

optimize lifecycle, if anyone server emit error, it's all stop.

optimize lifecycle 

---

pkg/defers/defer.go

fixes #122 
keep the simple code

fixes #122 

---

pkg/server/governor/server.go
pkg/server/xecho/server.go
pkg/server/xgin/server.go

fix service name for registry

---

jupiter.go
jupiter_test.go

add unit test

---

example/build/Makefile
example/build/config.toml
example/build/main.go
example/build/script/gobuild.sh
example/build/script/report_build_info.sh
example/config/structByFileWatch/config.toml
example/config/structByFileWatch/main.go
example/helloworld/config.toml
example/logger/fileByWatch/config/config.toml
pkg/pkg.go
tools/jupiter/new/templates/cmd/main.go.tmpl

fix go tool example
* add jupiter build example
* fix tool example

add jupiter build example

---

pkg/server/xgoframe/config.go
pkg/server/xgoframe/middleware.go
pkg/server/xgoframe/server.go

fix xgof regrister name and format code
-

fix xgof regrister name and format code

---

pkg/registry/etcdv3/registry.go

fix bug: for CopyStruct with a zero value error

fix regrister watch

---

example/grpc/direct/direct-client/main.go
pkg/xgrpclog/logger.go

issue:  https://github.com/douyu/jupiter/issues/140#issue-672769777

Use xlog.Logger for gprc log output

---

example/logger/file/config.toml
pkg/server/governor/config.go
pkg/util/xnet/ip.go

fix governor ip

---

go.mod
go.sum
jupiter.go
jupiter_option.go

jupiter support option

---

jupiter.go
jupiter_option.go

add disable governor option

---

pkg/server/governor/config.go
pkg/util/xnet/ip.go

modify governor require ip method
use udp protocol.
go run example/http/gin/main.go --config example/http/gin/config.toml

fix for issue #159

---

pkg/registry/etcdv3/registry.go

using Etcd client session  package  for keeping  lease id to live 
go run example/simple/main.go --config example/simple/config.toml

Dev etcd lease session

---

tools/jupiter/common/util.go
tools/jupiter/common/util_test.go

fix this issue : https://github.com/douyu/jupiter/issues/173

chore(tools/jupiter): fix duplicate for loop #173

---

jupiter.go

chore: add HideBanner field in application

---

pkg/client/redis/redis_cmds.go

feat : add scan operation for redis

---

pkg/registry/etcdv3/registry.go

feat:禁用与启用grpc

---

pkg/client/etcdv3/client.go

Improve code readability&reduce memory copy

enhance:Improve code readability&reduce memory copy

---

example/config/structByFileWatch/main.go
example/config/structByRemoteConfigWatch/main.go

Change-Id: I4a33087176fcce8ed42f4f9afa5d1fbc02625f43
当前的example不够严谨，如果被经验较少的开发者拷贝到线上项目中可能造成panic严重后果

fix: Better robustness

---

.github/workflows/codeql-analysis.yml

feat: support codeql

---

.github/semantic.yml

feat: add semantic check for pr

---

.github/workflows/go.yml
.github/workflows/goreleaser.yml
.goreleaser.yml

feat: support auto release by goreleaser

---

.github/stale.yml

ci: add stale yml

---

pkg/application/application_test.go
pkg/constant/env.go
pkg/env.go
pkg/pkg.go
pkg/xlog/config.go

application test clean
add app.stop recive chan

feat: improve log

---

pkg/registry/etcdv3/registry.go

fix: fix ttl session injection to etcd3

---

example/go.mod
example/go.sum
internal/hooks/hooks.go
internal/hooks/hooks_test.go
jupiter.go
pkg/application/application.go
pkg/application/application_test.go
pkg/server/xgin/config.go
pkg/server/xgoframe/config.go

fix: get host flag for gin and goframe

---

internal/hooks/hooks.go
internal/hooks/hooks_test.go
jupiter.go
pkg/application/application.go
pkg/application/application_test.go

feat: support hooks

---

README.md

docs: update contributors and contact

---

pkg/metric/metric.go

feat: improve metric

---

pkg/util/xcrypto/aes.go
pkg/util/xreflect/reflect.go
pkg/util/xreflect/reflect_test.go
pkg/util/xstring/string.go
pkg/util/xstring/string_test.go

feat: add util/xreflect util/xcrypto

---

pkg/conf/conf.go

fix: 修复配置文件监听nil chan

---

pkg/client/rocketmq/option.go
pkg/client/rocketmq/producer.go

chore: improve mq instanceName

---

pkg/client/rocketmq/consumer.go
pkg/client/rocketmq/e2e_test.go
pkg/client/rocketmq/init.go
pkg/client/rocketmq/interceptor.go
pkg/client/rocketmq/option.go
test/testdata/rocketmq/conf/rocketmq.toml

feat: rocketmq support tracing

---

.github/workflows/lint-go.yml

chore: update lint ci

---

pkg/flag/flag.go

fix: 传入Variable时，flag重复调用导致失败

---

pkg/client/rocketmq/consumer.go
pkg/client/rocketmq/option.go

fix: change rocketmq config to pointer

---

cmd/jupiter/internal/cmd/cmd_new.go

feat: improve speed to clone layout

---

go.mod
go.sum

chore: downgrade echo to v4.1.16

---

README.md

docs: improve quick start doc

---

pkg/xlog/config.go

fix: log naming

---

pkg/sentinel/testdata/flow.toml

fix: test error

---

.github/workflows/go.yml

ci: add 1.19.x for test

---

pkg/store/gorm/option.go
pkg/store/gorm/option_test.go
pkg/store/gorm/orm.go
pkg/store/gorm/orm_test.go
pkg/store/mongox/option.go

chore: improve code style

---

pkg/util/xnet/ip.go

modify a wrong character in pkg/util/xnet/ip.go:24

fix: typo in return error

---

pkg/client/redis/config.go

fix: 修复redis配置单个地址会报错

---

.github/workflows/go.yml

ci: support build on macos and windows

---

go.mod
pkg/store/gorm/option.go
pkg/store/gorm/orm.go
pkg/xlog/api.go

chore: improve bump up process

---

.github/workflows/go.yml
go.mod
go.sum
pkg/client/grpc/balancer/p2c/least_loaded_test.go
pkg/client/grpc/client.go
pkg/store/gorm/option_test.go

feat: bump grpc-go to latest version

---

cmd/jupiter/internal/cmd/cmd.go
cmd/jupiter/internal/cmd/cmd_init.go

feat: jupiter support init cmd

---

pkg/conf/conf.go
pkg/util/xcast/cast.go
pkg/util/xcast/cast_test.go

feat: add int64Slice

---

pkg/xlog/api.go
pkg/xlog/context.go

feat: improve log logic

---

pkg/application/application.go

feat: support autoproc

---

pkg/sentinel/sentinel_circuitbreaker_test.go
pkg/xlog/log_test.go

fix: metric naming and test case

---

pkg/client/etcdv3/config.go
pkg/client/grpc/config.go
pkg/client/grpc/interceptor.go
pkg/client/rocketmq/option.go
pkg/constant/config.go
pkg/sentinel/config.go
pkg/server/xgrpc/config.go
pkg/server/xgrpc/interceptor.go
pkg/store/gorm/option.go
pkg/xlog/config.go
pkg/xtrace/init.go
pkg/xtrace/jaeger/config.go
pkg/xtrace/trace.go

chore: improve xtrace

---

pkg/client/grpc/config.go
pkg/client/redis/config.go
pkg/client/resty/resty.go
pkg/core/registry/etcdv3/config.go
pkg/core/registry/init.go
pkg/server/governor/config.go
pkg/server/xecho/config.go
pkg/server/xfasthttp/config.go
pkg/server/xgin/config.go
pkg/server/xgoframe/config.go
pkg/server/xgrpc/config.go
pkg/store/gorm/option_test.go
pkg/store/mongox/mongo.go
pkg/store/mongox/option.go
pkg/store/mongox/option_test.go
pkg/worker/xcron/config.go
tools/ast_codes/main.go

feat: using common config key prefix

---

pkg/core/singleton/singleton.go
pkg/core/singleton/singleton_test.go

fix: add singleton unit test

---

pkg/client/etcdv3/watch.go
pkg/client/grpc/client.go
pkg/client/grpc/client_test.go
pkg/client/grpc/common_test.go
pkg/client/grpc/config.go
pkg/client/grpc/config_test.go
pkg/client/grpc/resolver/resolver.go
pkg/registry/etcdv3/registry.go
pkg/registry/etcdv3/registry_test.go
pkg/registry/nop.go
pkg/registry/registry.go
pkg/server/server.go

feat!: migrate all stuff with breaking changes

---

.github/release.yml

feat: add release yml to improve changelog

---

pkg/client/etcdv3/config.go
pkg/client/grpc/client.go
pkg/client/grpc/client_test.go
pkg/client/grpc/common_test.go
pkg/client/grpc/config.go
pkg/client/grpc/config_test.go
pkg/client/grpc/dns_test.go
pkg/client/grpc/etcd_test.go
pkg/core/application/application_test.go
pkg/core/executor/xxl/Readme.md
pkg/core/executor/xxl/executor_test.go
pkg/core/executor/xxl/options.go
pkg/core/executor/xxl/options_test.go
pkg/xlog/config.go
pkg/xlog/log.go

feat: improve grpc with more test case

---

pkg/client/etcdv3/client_test.go
pkg/client/etcdv3/config.go
pkg/client/etcdv3/config_test.go
pkg/client/etcdv3/watch_test.go

chore: fix etcd test case

---

pkg/client/grpc/client.go
pkg/core/application/application.go
pkg/core/xgrpclog/logger.go

fix: grpclog data race

---

pkg/client/redis/client.go
pkg/client/redis/client_test.go
pkg/client/redis/config.go
pkg/client/redis/config_test.go
pkg/client/redis/init.go
pkg/client/redis/interceptor.go
pkg/client/redis/interceptor_test.go

feat: redisgo rename to redis

---

pkg/client/grpc/config.go

fix: grpc config name

---

pkg/registry/etcdv3/registry.go
pkg/registry/etcdv3/update.go
pkg/server/server.go
pkg/server/server_test.go

feat: add metadata for etcd registry

---

pkg/client/grpc/client.go
pkg/registry/etcdv3/registry_test.go

fix: registry test case failed sometimes

---

pkg/client/grpc/client_test.go
pkg/client/rocketmq/interceptor.go
pkg/core/xtrace/otelgrpc/config.go
pkg/registry/etcdv3/registry_test.go

fix: add grpc test for async connect

---

go.mod
go.sum
pkg/core/cmd/cmd_new.go

feat: support new single app

---

pkg/executor/xxl/executor.go

fix: xxljob register addr

---

pkg/util/xerror/errors.go
pkg/util/xerror/errors_test.go

feat: xerror support nil

---

pkg/client/grpc/config.go
pkg/client/grpc/interceptor.go
pkg/client/redis/client.go
pkg/client/redis/config.go
pkg/client/redis/interceptor.go
pkg/client/rocketmq/consumer.go
pkg/client/rocketmq/interceptor.go
pkg/client/rocketmq/producer.go
pkg/core/sentinel/config.go
pkg/core/sentinel/sentinel.go
pkg/core/sentinel/sentinel_circuitbreaker.go
pkg/server/xecho/config.go
pkg/server/xecho/middleware.go
pkg/server/xgrpc/config.go
pkg/server/xgrpc/interceptor.go
pkg/store/gorm/interceptor.go
pkg/store/gorm/orm.go

feat: support sentinel for server and client 

---

pkg/core/sentinel/config.go
pkg/core/sentinel/sentinel_circuitbreaker_test.go

fix: sentinel load rules

---

pkg/conf/conf_test.go
pkg/pkg.go

test: add conf test case

---

.github/workflows/e2e-test.yml
Makefile
go.mod
pkg/client/grpc/client.go
pkg/client/grpc/common_test.go
pkg/client/grpc/config.go
pkg/core/tests/grpc.go
pkg/core/tests/http.go
pkg/core/tests/redis.go
test/e2e/client/redis.go
test/e2e/e2e_test.go
test/e2e/go.mod
test/e2e/go.sum
test/e2e/server/xecho.go
test/e2e/server/xfasthttp.go
test/e2e/server/xgin.go
test/e2e/server/xgoframe.go
test/e2e/server/xgrpc.go
test/e2e/server/xgrpcgateway.go

test: add redis e2e test

---

.github/workflows/lint.yml
.github/workflows/unit-test.yml

ci: improve lint

---

CHANGELOG.md
pkg/pkg.go

chore: release v0.9.11

---

.github/workflows/unit-test.yml
go.mod
go.sum
pkg/core/constant/module.go
pkg/core/metric/metric.go
pkg/store/tablestore/README.md
pkg/store/tablestore/init.go
pkg/store/tablestore/instance.go
pkg/store/tablestore/instance_test.go
pkg/store/tablestore/option.go
pkg/store/tablestore/option_test.go

feat: support tablestore client

---

.github/workflows/lint.yml
.github/workflows/unit-test.yml
pkg/store/tablestore/instance_test.go

feat: improve ci test

---

pkg/conf/conf.go
pkg/conf/conf_test.go
pkg/util/xcast/cast.go

fix: GetInt64Slice

---

CHANGELOG.md
pkg/pkg.go

chore: release v0.9.13

---

pkg/server/xecho/server.go
pkg/server/xecho/server_test.go
pkg/server/xgrpc/server.go
pkg/server/xgrpc/server_test.go

feat: add xecho api and  xgrpc method display on console

---

CHANGELOG.md
README.md
pkg/pkg.go

chore: bump to v0.10.0

---

pkg/client/rocketmq/interceptor.go

chore: change rocketmq consumer log level

---

CHANGELOG.md
pkg/pkg.go

chore: release v0.10.1

---

pkg/client/grpc/client.go
pkg/client/grpc/client_test.go
pkg/client/grpc/common_test.go
pkg/client/grpc/config.go
pkg/client/grpc/dns_test.go
pkg/client/grpc/etcd_test.go
pkg/core/tests/grpc.go

fix: grpc test case for grpc-go v1.52.0

---

pkg/server/xecho/middleware.go
pkg/xlog/log_test.go

fix: cost uint for echo's access log

---

pkg/server/xgrpc/config.go
pkg/server/xgrpc/server.go
pkg/server/xgrpc/server_test.go

fix: grpc intercept order

---

pkg/client/etcdv3/client.go
pkg/client/grpc/config.go

fix: grpc keepalive time

---

CHANGELOG.md
pkg/pkg.go

chore: bump jupiter to v0.10.2

---

.gitattributes

fix: golangci-lint failure caused by windows CRLF

---

cmd/jupiter/main.go
cmd/protoc-gen-go-xerror/main.go
cmd/protoc-gen-go-xerror/xerror.go

fix: remove unused code and use jupiter version

---

pkg/server/init.go

feat: get default host instead of 127.0.0.1

---

pkg/client/rocketmq/producer.go

fix one application can not start two producer

fix: add producer group name for rocketmq

---

pkg/util/xgo/goroutine.go

pref: RestrictParallel exec opti #778

perf: RestrictParallel exec opti

---

pkg/xlog/log.go

feat: print log to console in dev mode

---

pkg/util/xnet/address.go
test/e2e/jupiter/grpc.go

fix: grpc listen host

---

CHANGELOG.md
pkg/pkg.go

chore: bump jupiter to v0.11.5

---

pkg/client/resty/resty_test.go
test/docker-compose.yaml

feat: add httpbin in docker-compose

---

pkg/cache/xfreecache/v2/cache.go
pkg/cache/xfreecache/v2/cache_test.go
pkg/cache/xfreecache/v2/localcache.go

feat(freecache): fix nil not hit

---

pkg/registry/etcdv3/registry.go
pkg/registry/update.go

fix: be compatible with old grpc client

---

go.mod
go.sum

chore: bump rocketmq-client-go

---

pkg/server/governor/config.go

fix: govern host and port

---

pkg/cache/xfreecache/v2/cache.go
pkg/cache/xfreecache/v2/cache_null_test.go

feat(freecache): fix null value

---

go.mod
go.sum
pkg/client/rocketmq/option.go

fix: rocketmq unable to rebalance after adding queues

---

pkg/core/metric/metric.go

feat: add customized metrics

---

pkg/client/grpc/balancer/p2c/least_loaded_test.go

fix: grpc test package

---

go.mod
pkg/pkg.go

chore: bump jupiter to v0.11.10

---

go.mod
go.sum
pkg/core/xtrace/trace.go
pkg/server/xecho/middleware.go
pkg/server/xgin/middleware.go
pkg/server/xgrpc/interceptor.go

feat: otel be compatible with opentracing

---

pkg/client/rocketmq/push_consumer.go
test/e2e/go.mod
test/e2e/go.sum

feat: mq push consume supports ratelimit

---

.github/workflows/unit-test.yml
pkg/client/redis/cluster.go
pkg/client/redis/cluster_test.go

修复redis cluster 单测异常
Fixes #xxxx

fix: 修改cluster 单测

---

.github/workflows/unit-test.yml
pkg/client/redis/cluster_test.go
test/data/cluster/conf/nodes.conf
test/docker-compose.yaml

fix cluster node conf
fix cluster node conf
modify node conf

fix: cluster调整成单节点集群

---

.github/workflows/e2e-test.yml
.github/workflows/unit-test.yml
test/docker-compose.yaml

fix: ci yaml

---

pkg/pkg.go

chore: bump to v0.11.12

---

.github/release.yml

chore: add bug and dependencies in release notes

---

pkg/client/rocketmq/option.go

fix: consumer enbale true by default

---

README.md

docs: fix docker compose

---

pkg/core/xtrace/jaeger/config.go

feat: improve otel with resource

---

pkg/server/xecho/middleware.go

fix: do not record ip in metric

---

go.mod
go.sum

feat(xgolanglru): improve

---

website/docs/jupiter/4.9freecache.md

feat(cache): improve md

---

.github/workflows/e2e-test.yml

chore: Update e2e-test.yml

---

.github/workflows/e2e-test.yml
.github/workflows/unit-test.yml
README.md
go.mod
go.sum
test/docker-compose.yaml
website/docs/juno/1.1quickstart.md
website/docs/juno/1.4install_docker_compose.md
website/docs/jupiter/1.1quickstart.md

fix: docker compose

---

.github/workflows/e2e-test.yml
.github/workflows/unit-test.yml

fix: codecov upload
