douyu/jupiter

- pkg/util/xfile/file.go
Fixed the connection profile path bug when Windows started up
Fixes #5 
The getParentDirectory function adds a judgment to the Windows system
Use the Windows system to start juno-agent. The command is juno-agent --config=../../ config/config-live. toml
> Fixed the connection profile path bug when Windows started up

- example/http/gin/main.go
- example/http/gin_ws_cors/config.toml
- example/http/gin_ws_cors/main.go
xgin->websocket 例子`jupiter/example/http/gin/main.go`不允许跨域，报以下错误：
`upgrade:websocket: request origin not allowed by Upgrader.CheckOrigin`
Fixes #167 
通过预留方法WebSocketOption，设置websocket允许跨域
使用websocket在线测试工具，测试得到websocket允许跨域
> xgin->websocket，允许websocket跨域

- pkg/worker/xcron/config.go
cron默认没有解析器，需要设置withSeconds为true，默认情况下，cron解析器应该解析到分钟。
> add default cron parser

- pkg/server/governor/config.go
- pkg/server/governor/server.go
- pkg/server/xecho/config.go
- pkg/server/xecho/handler.go
- pkg/server/xecho/server.go
- pkg/server/xgin/config.go
- pkg/server/xgin/server.go
- pkg/server/xgoframe/config.go
- pkg/server/xgoframe/server.go
- pkg/server/xgrpc/config.go
- pkg/server/xgrpc/server.go
- pkg/server/xgrpc/server_test.go
support for customizing service-address in registry info
支持自定义服务注册信息中的服务地址，用于服务访问地址和服务Listen的地址不一致的情况
NONE
Add `ServiceAddress` field to `xecho.Config`, `xgrpc.Config`, `xgin.Config`, `xgoframe.Config`
1. start a `xecho/xgrpc/xgin/xgoframe` server with `ServiceAddress` set
2. check etcd key
NONE
> support for customizing service-address in registry info

- pkg/util/xcolor/string_darwin.go
- pkg/util/xcolor/string_linux.go
- pkg/util/xcolor/string_windows.go
- pkg/util/xcolor/util.go
- pkg/util/xcolor/xcolor_test.go
print one color to distinguish two different funcs, which is not very useful for developers. If you need to add other colors, you also need to declare two funcs, which is not very good from a design perspective.This PR further optimizes xcolor to improve the developer experience
Combine and optimize functions
fmt.Println(xcolor.Red("hello")) -> fmt.Println(xcolor.Red("hello"))
hello              ->        hello
fmt.Println(xcolor.Red("hello", "world")) -> fmt.Println(xcolor.Redf("hello", "world"))
hello world   ->     hello world
> optimize xcolor

- pkg/util/xstring/string.go
将int64转化为uint16的时候可能会发生越界，应该采用这种PraseUint的方法并且指定比特位数为16
> fix: incorrect conversion between integer types

- pkg/server/xgrpc/config.go
- pkg/server/xgrpc/server.go
> feat: grpc support tls

- .github/workflows/go.yml
- go.mod
- go.sum
- jupiter_option.go
- pkg/application/application_test.go
- pkg/client/rocketmq/consumer.go
- pkg/client/rocketmq/e2e_test.go
- pkg/client/rocketmq/init.go
- pkg/client/rocketmq/option.go
- pkg/client/rocketmq/producer.go
- pkg/istats/flow_info.go
- pkg/util/xcycle/lifecycle_test.go
- test/testdata/rocketmq/conf/rocketmq.toml
> feat: enhance client/rocketmq

- example/client/rocketmq/config.toml
- example/client/rocketmq/main.go
- pkg/client/rocketmq/consumer.go
- pkg/client/rocketmq/interceptor.go
- pkg/client/rocketmq/option.go
- pkg/client/rocketmq/producer.go
> feat: add batch consumer message

- pkg/util/xerror/code_msg.go
- pkg/util/xerror/errors.go
- pkg/util/xerror/errors_test.go
> feat: add xerror pkg

- go.mod
在使用当前项目的 `go.mod` 规定的最小go版本，不能正确处理依赖相关的库。
这个 pr 已经修复上述问题
修改 go.mod 最低支持的版本为 go1.16
执行 `go mod tidy`
> fix: update go mod version to go1.16

- pkg/util/xgeneric/go.mod
- pkg/util/xgeneric/go.sum
- pkg/util/xgeneric/slice.go
- pkg/util/xgeneric/slice_test.go
> feat: add xgeneric for go1.18

- cmd/jupiter/README.MD
- cmd/jupiter/internal/cmd/cmd.go
- cmd/jupiter/internal/cmd/cmd_clean.go
- cmd/jupiter/internal/cmd/cmd_new.go
> feat:  add cache and clean features

- .github/workflows/pr.yml
> feat: add pr.yml to check title

- cmd/jupiter/internal/cmd/cmd.go
- cmd/jupiter/internal/cmd/cmd_clean.go
- cmd/jupiter/internal/cmd/cmd_new.go
> feat(cmd): add auto upgrade(#341)

- pkg/application/application.go
> fix: 解决ctrl+c导致data race 问题

- pkg/application/application.go
- pkg/client/rocketmq/consumer.go
- pkg/client/rocketmq/producer.go
- pkg/hooks/hooks.go
> feat: start mq before run

- pkg/xlog/api.go
- pkg/xlog/log.go
> feat: add basic api for log

- pkg/xlog/api.go
- pkg/xlog/config.go
- pkg/xlog/field.go
- pkg/xlog/log.go
> feat: add default api for xlog

- README.md
- pkg/application/application.go
- pkg/client/etcdv3/client.go
- pkg/client/etcdv3/config.go
- pkg/client/etcdv3/intercept.go
- pkg/client/grpc/interceptor.go
- pkg/client/resty/resty.go
- pkg/client/rocketmq/consumer.go
- pkg/client/rocketmq/init.go
- pkg/client/rocketmq/interceptor.go
- pkg/client/rocketmq/log.go
- pkg/client/rocketmq/option.go
- pkg/client/rocketmq/producer.go
- pkg/hooks/hooks.go
- pkg/hooks/hooks_test.go
- pkg/registry/etcdv3/registry.go
- pkg/server/xecho/middleware.go
- pkg/server/xgin/middleware.go
- pkg/server/xgrpc/config.go
- pkg/server/xgrpc/interceptor.go
- pkg/store/gorm/interceptor.go
- pkg/xtrace/jaeger/config.go
- pkg/xtrace/utils.go
> feat: improve tracing with otel

- pkg/application/application.go
- pkg/autoproc/autoproc.go
> feat: Optimize the use of gomaxprocs

- .github/workflows/go.yml
- pkg/client/rocketmq/consumer.go
- pkg/client/rocketmq/init.go
- pkg/client/rocketmq/producer.go
- test/data/broker/conf/broker.conf
- test/docker-compose.yaml
- test/testdata/rocketmq/conf/rocketmq.toml
> feat: improve workflow and refactor rocketmq

- pkg/application/application.go
unregister before stop
unregistered before stop and graceful stop
> feat: unregister before stop

- pkg/client/etcdv3/client.go
- pkg/client/grpc/client.go
- pkg/client/grpc/config.go
- pkg/client/grpc/config_test.go
- pkg/client/grpc/resolver/resolver.go
- pkg/registry/etcdv3/config.go
- pkg/registry/init.go
- pkg/util/xgo/init.go
> feat: improve registry implementation

- pkg/core/cmd/cmd_new.go
- pkg/core/cmd/cmd_test.go
- pkg/registry/etcdv3/registry_test.go
- pkg/server/server.go
- pkg/server/server_test.go
> feat: jupiter support create templates from specified git branch

- .codecov.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/coverage.xml
- .github/workflows/go.yml
> fix: improve ci logic

- pkg/client/redis/config.go
- pkg/client/redis/interceptor.go
- pkg/client/redis/interceptor_test.go
- website/docs/jupiter/6.8clientredis.md
> feat: redis record traceid without open trace

- pkg/client/redis/config.go
- pkg/client/redis/config_test.go
> fix: redis RawConfigsimplify

- pkg/client/redis/interceptor.go
- pkg/client/redis/interceptor_test.go
- pkg/client/rocketmq/consumer.go
- pkg/client/rocketmq/interceptor.go
- pkg/client/rocketmq/option.go
- pkg/client/rocketmq/producer.go
- pkg/server/xecho/middleware.go
- pkg/server/xgrpc/interceptor.go
- pkg/xlog/context.go
- pkg/xlog/log_test.go
> fix: trace integration

- pkg/client/rocketmq/consumer.go
> fix: the var of span occurrence Unexpected.#571

- pkg/core/tests/grpc.go
- pkg/core/tests/http.go
> feat: improve test tool

- CHANGELOG.md
- pkg/pkg.go
> chore: bump v0.9.12

- .github/workflows/unit-test.yml
> fix: use pull_request_target instead of pull_request

- pkg/server/xgrpc/server.go
> feat: support reflection for grpc

- pkg/server/governor/server.go
- pkg/server/init.go
- pkg/server/server.go
- pkg/server/xecho/config.go
- pkg/server/xecho/server.go
- pkg/server/xfasthttp/server.go
- pkg/server/xgin/server.go
- pkg/server/xgrpc/server.go
- pkg/util/xnet/address.go
- pkg/util/xnet/address_test.go
> feat: get register address from listener

- pkg/core/sentinel/sentinel_circuitbreaker_test.go
- pkg/core/sentinel/testdata/circuitbreaker.toml
> chore: improve timeout test case

- pkg/cache/xfreecache/v2/cache.go
- pkg/cache/xfreecache/v2/cache_bench_test.go
- pkg/cache/xfreecache/v2/encode.go
- pkg/cache/xfreecache/v2/encode_bench_test.go
> feat(freecache): race问题

- pkg/cache/xfreecache/v2/cache.go
- pkg/cache/xfreecache/v2/cache_test.go
- website/docs/jupiter/4.9freecache.md
> feat(freecache): 新增单独获取和设置本地缓存的方法

- go.mod
- go.sum
- pkg/client/rocketmq/option.go
> refactor: nolint dupl

- proto/helloworld/v1/echo_test.go
- proto/helloworld/v1/gin_test.go
use res.Body.Bytes() instead of []byte(res.Body.String())
> chore: use res.Body.Bytes() instead of []byte(res.Body.String())

- pkg/client/rocketmq/push_consumer.go
- pkg/server/xecho/config.go
- pkg/server/xecho/middleware.go
- pkg/server/xgrpc/interceptor.go
- pkg/xlog/api.go
- pkg/xlog/context.go
- pkg/xlog/log_test.go
There is no trace id field in the `xecho access log`, but we do need it.
Just replace the default logger in the middleware
The trace id field is included in the output access log
> feat: update xecho access log with trace id

- pkg/client/rocketmq/push_consumer.go
1. Causing the queue goroutine to exit processing msg panic
2. Then should add recover() function to prevent exit and continue process the msg.
> fix: queue to exit when mq processing msg panic

- pkg/client/rocketmq/producer.go
This pull request adds two new methods to the Producer struct in the RocketMQ package. The `SendWithResult` method allows sending messages with a custom tag and returns the send result. The `SendMsg` method is used for sending messages with a custom message format.
NONE
I added two new methods to the Producer struct: `SendWithResult` and `SendMsg`. The `SendWithResult` method constructs a new message with a specified tag and sends it synchronously, returning the send result. The `SendMsg` method sends a custom message using the provided Message struct.
To verify this change, you can follow these steps:
1. Use the `SendWithResult` method with a custom message and tag to send a message and verify that it returns the send result.
2. Use the `SendMsg` method with a custom Message struct to …
> feat: rocketmq add util func

- pkg/server/xecho/handler.go
don't modify the default binder of echo server
changing default binder of echo server will cause the problem that some controllers cannot get the query params .
1 request a grpc proxy wrapper controller 
2 request a normal get controller  
3 the  normal controller cannot get the correct query param
> fix: fix grpc proxy wrapper modify binder

- pkg/client/resty/resty.go
- pkg/client/rocketmq/interceptor.go
- pkg/core/xtrace/propagation.go
- pkg/core/xtrace/trace.go
- pkg/server/xecho/middleware.go
- pkg/server/xgrpc/interceptor.go
- pkg/store/gorm/interceptor.go
> feat: fully compatible with opentracing
